version: '3'

services:
  php_env:
    build: .
    volumes:
      - ./HiveGame:/var/www/html
    ports:
      - 8000:80
    networks:
      - my_network

  Mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - my_network

  app-ai:
    build:
      context: .
      dockerfile: Dockerfile.Al
    ports:
      - "5000:5000"

networks:
  my_network:



