version: '3'

services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile.JEN
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkinsnet

  sonarqube:
    container_name: sonarqube
    build:
      context: .
      dockerfile: Dockerfile.Qube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    networks:
      - jenkinsnet

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8082:80"
    networks:
      - jenkinsnet

networks:
  jenkinsnet:

volumes:
  jenkins_home:
